---
# ====== Application: Diamond Trust Bank - Service Provider ==
id: 125
identification: 
  name: Diamond Trust Bank - Service Provider
  alias: DIAMOND-TRUST-BANK124125
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: customauthN # 47491150006182692

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify Workspace Repository

database-session: 
  parsing-schema: WKSP_WSDTBDEV

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Diamond Trust Bank

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 66506188160849807

navigation-bar: 
  implementation: List
  list: Navigation Bar # 66507297952849765
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: true

subscription: 
  version-number: 45778980653657

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Diamond Trust Bank

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 66500911295849839
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 45684430851446

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 66501183194849834
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 45684430851612

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 66501491995849833
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 45684430851758

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 66501797608849832
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 45684430851759

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 66502115875849831
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 45684430851766

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 66502352832849830
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 45684430851893

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 66502641953849829
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 45684430851908

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 66502983232849828
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 45684430851961

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 66503288523849827
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 45684430851961

- # ====== Component Setting: NATIVE_IR ========================
  id: 66503588192849825
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 45684430852061

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 66503868785849824
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 45684430852068

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 66504137961849823
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 45684430852068

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 66504446360849822
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 45684430852068

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 66504781764849821
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 45684430852070

